
CREATE TABLE Users(
	ID INTEGER PRIMARY KEY,
	name VARCHAR(30) NOT NULL,
	surname VARCHAR(30) NOT NULL,
	password VARCHAR(30) NOT NULL,
	email VARCHAR(30) NOT NULL,
	birth DATE
);

CREATE TABLE Address(
	ID INTEGER PRIMARY KEY,
	street VARCHAR(30) NOT NULL,
	civicNumber INTEGER NOT NULL,
	city VARCHAR(30) NOT NULL,
	CAP VARCHAR(5) NOT NULL,
	province VARCHAR(2) NOT NULL,
	phone VARCHAR(30)
);

CREATE TABLE Deliver(
	user INTEGER,
	address INTEGER,
	PRIMARY KEY (user, address),
	FOREIGN KEY user REFERENCES Users(ID),
	FOREIGN KEY address REFERENCES Address(ID)
);

CREATE TABLE Category(
	ID INTEGER PRIMARY KEY,
	name VARCHAR(30) NOT NULL
)

CREATE TABLE Producer(
	ID INTEGER PRIMARY KEY,
	name VARCHAR(30) NOT NULL
)

CREATE TABLE Product(
	ID INTEGER PRIMARY KEY,
	name VARCHAR(30) NOT NULL,
	description VARCHAR(200),
	year YEAR NOT NULL,
	language VARCHAR(3),
	price FLOAT NOT NULL,
	available BOOLEAN NOT NULL,
	imageURL VARCHAR(40),
	category INTEGER NOT NULL,
	producer INTEGER NOT NULL,
	FOREIGN KEY category REFERENCES Category(ID),
	FOREIGN KEY producer REFERENCES Producer(ID)
)

CREATE TABLE Status(
	ID INTEGER PRIMARY KEY,
	status VARCHAR(15) NOT NULL
)

CREATE TABLE Order(
	ID INTEGER PRIMARY KEY,
	orderDate DATE NOT NULL,
	deliveryEstimate DATE,
	user INTEGER NOT NULL,
	address INTEGER NOT NULL,
	status INTEGER NOT NULL,
	FOREIGN KEY user REFERENCES User(ID),
	FOREIGN KEY address REFERENCES Address(ID),
	FOREIGN KEY status REFERENCES Status(ID)
)

CREATE TABLE Buy(
	order INTEGER NOT NULL,
	product INTEGER NOT NULL,
	PRIMARY KEY (order, product),
	FOREIGN KEY order REFERENCES Order(ID),
	FOREIGN KEY product REFERENCES Product(ID),
)
